### ISSUE TITLE
2023/24 CBB box scores not uploading

### ISSUE THREAD

**Issue by dbaggot3** [sportsdataverse/hoopR-mbb-data#1]
Hi there,

Hate to be a bother, but it doesn't look like the current season of box scores for CBB haven't been updated. The only data that appears to show the current 2024 season is the schedule.

<img width="1091" alt="Screenshot 2023-11-08 at 8 10 06 AM" src="https://github.com/sportsdataverse/hoopR-mbb-data/assets/91554869/84ae14f6-c451-45bd-82c2-6c96e6fb45af">

Thanks in advance for your help!

Declan

**Comment by dbaggot3** [comment]
Hello again, is there any update on this?

**Comment by saiemgilani** [comment]
Should be resolved now, please confirm

**Comment by dbaggot3** [comment]
Yes, looks like the functions return the proper 2024 data - thanks for the fix!
